# Config file for automatic testing at travis-ci.org
language: python
cache: pip

services:
  - docker

before_install:
  - docker-compose -v
  - docker -v

install: pip install -r requirements.txt

matrix:
  include:
    - name: Test Python 3.6
      python: 3.6
      script: ./scripts/clean.sh && ./scripts/test.sh
    - name: Test Python 3.7
      python: 3.7
      script: ./scripts/clean.sh && ./scripts/test.sh
    - name: Lint
      python: 3.7
      script: ./scripts/lint.sh
